services:
  - type: web
    name: Portfolio
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn demoproject.wsgi:application"
    runtime:
      pythonVersion: 3.10.12
