services:
  - type: web
    name: Portifolio
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn demoproject.wsgi:application"
    runtime:
      pythonVersion: "3.10.12"
